exports.createQuizQuery = "INSERT INTO QUIZ_DTLS SET QUIZ_ID=?,PUBLISHED=?,USER_ID=?"

exports.publishQuizQuery = "UPDATE QUIZ_DTLS SET PUBLISHED=?, CODE=?, WHERE QUIZ_ID=?"


exports.deleteQuizQuery = " DELETE FROM QUIZ_DTLS WHERE QUIZ_ID=?"


exports.createQuestion = "INSERT INTO QUIZ_QUESTIONS SET QUES_ID=?,QUES_DESCREPTION=?,QUES_TYPE=?,OPTION1=?,OPTION1=?,OPTION3=?,OPTION4=?,ANSWER=?,QUIZ_ID=?"