-- User Details
CREATE TABLE IF NOT EXISTS USER_DTLS(
        USER_ID VARCHAR(255) PRIMARY KEY,
        EMAIL_ADDRESS VARCHAR(200) NOT NULL UNIQUE,
        PASSWORD VARCHAR(200) NOT NULL UNIQUE,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE  CURRENT_TIMESTAMP
);

--Quiz Details 
CREATE TABLE IF NOT EXISTS QUIZ_DTLS(
        QUIZ_ID VARCHAR(255) PRIMARY KEY,
        PUBLISHED BOOLEAN DEFAULT FALSE,
        CODE VARCHAR(255),
        USER_ID VARCHAR(255),
        FOREIGN KEY (USER_ID) REFERENCES USER_DTLS(USER_ID)
);

-- Question details
CREATE TABLE IF NOT EXISTS QUIZ_QUESTIONS (
QUES_ID VARCHAR( 255) PRIMARY KEY ,
QUES_DESCREPTION VARCHAR(255) NOT NULL UNIQUE, 
QUES_TYPE VARCHAR(255) NOT NULL,
OPTION1 VARCHAR(255),
OPTION2 VARCHAR(255),
OPTION3 VARCHAR(255),
OPTION4 VARCHAR(255),
ANSWER VARCHAR(255),
QUIZ_ID VARCHAR(255),
FOREIGN KEY (QUIZ_ID) REFERENCES QUIZ_DTLS(QUIZ_ID)
);
